/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exceptions_DelaunayException */

#ifndef _Included_exceptions_DelaunayException
#define _Included_exceptions_DelaunayException
#ifdef __cplusplus
extern "C" {
#endif
#undef exceptions_DelaunayException_serialVersionUID
#define exceptions_DelaunayException_serialVersionUID -3042686055658047285LL
#undef exceptions_DelaunayException_serialVersionUID
#define exceptions_DelaunayException_serialVersionUID -3387516993124229948LL
#undef exceptions_DelaunayException_serialVersionUID
#define exceptions_DelaunayException_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
