/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_DelaunayData */

#ifndef _Included_JNI_DelaunayData
#define _Included_JNI_DelaunayData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
